// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	GorpMigrations string
	Users          string
}{
	GorpMigrations: "gorp_migrations",
	Users:          "users",
}
