-- +migrate Up
CREATE TABLE IF NOT EXISTS users (
    `id` BIGINT NOT NULL AUTO_INCREMENT, 
    `name` VARCHAR(30) NOT NULL,
    `email` VARCHAR(319) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
    ) ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4;

-- +migrate Down
DROP TABLE IF EXISTS users;