// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package httpserver

import (
	"github.com/masato-MacbookPro/go-chat/internal/app/httpserver/app"
	"github.com/masato-MacbookPro/go-chat/internal/app/httpserver/config"
	"github.com/masato-MacbookPro/go-chat/internal/app/httpserver/presentation/handler"
	"github.com/masato-MacbookPro/go-chat/internal/infrastructure"
	"github.com/masato-MacbookPro/go-chat/internal/infrastructure/repositoryimpl"
	"github.com/masato-MacbookPro/go-chat/internal/usecase"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, error) {
	appConfig := config.LoadConfig()
	mySQLInfo := appConfig.MySQLInfo
	db, err := infrastructure.NewMySQLConnector(mySQLInfo)
	if err != nil {
		return nil, err
	}
	userRepostitory := repositoryimpl.NewUserRepositoryImpl(db)
	userUsecase := usecase.NewUserUsecase(userRepostitory)
	userHandler := handler.NewUserHandler(userUsecase)
	appApp := app.NewApp(appConfig, userHandler)
	return appApp, nil
}
